window.cluesJSON = [
  { "title": "Finding Nemo", "clue": "Helicopter parent commits multiple felonies trying to retrieve his runaway son with a lucky blue amnesiac.", "category": "Family", "emoji": "🐠" },
  { "title": "Encanto", "clue": "Gifted family singles out their only un-magical member for vibes management.", "category": "Family", "emoji": "🐠" },
  { "title": "Finding Nemo", "clue": "Helicopter parent ignores maritime law to retrieve a truant guppy.", "category": "Family", "emoji": "🐠" },
  { "title": "Finding Dory", "clue": "A blue goldfish proves memory is optional for leadership.", "category": "Family", "emoji": "🐠" },
  { "title": "Toy Story", "clue": "Vintage cowboy loses workplace to plastic astronaut intern.", "category": "Family", "emoji": "🐠" },
  { "title": "Toy Story 3", "clue": "Daycare becomes maximum security for abandoned playthings.", "category": "Family", "emoji": "🐠" },
  { "title": "The Lion King", "clue": "Nephew returns from bug cleanse to reclaim cat monarchy.", "category": "Family", "emoji": "🐠" },
  { "title": "Moana", "clue": "Unlicensed teen sailor commits grand larceny against a volcano auntie.", "category": "Family", "emoji": "🐠" },
  { "title": "Shrek", "clue": "Swamp homeowner sues kingdom for HOA violations and wins a princess.", "category": "Family", "emoji": "🐠" },
  { "title": "The Incredibles", "clue": "Supers trade therapy for spandex and property damage.", "category": "Family", "emoji": "🐠" },
  { "title": "The Incredibles 2", "clue": "Mom gets the job, dad negotiates with baby laser union.", "category": "Family", "emoji": "🐠" },
  { "title": "Up", "clue": "Widower relocates via balloons; picks up Boy Scout and feelings.", "category": "Family", "emoji": "🐠" },
  { "title": "WALL-E", "clue": "Trash cube enthusiast saves humanity with excellent taste in musicals.", "category": "Family", "emoji": "🐠" },
  { "title": "Inside Out", "clue": "Five office workers in a child's head fumble a relocation project.", "category": "Family", "emoji": "🐠" },
  { "title": "Coco", "clue": "Kid gatecrashes ancestral potluck to chase guitar clout.", "category": "Family", "emoji": "🐠" },
  { "title": "Zootopia", "clue": "Bunny rookie uncovers predator panic and municipal sloth.", "category": "Family", "emoji": "🐠" },
  { "title": "Big Hero 6", "clue": "Inflatable nurse becomes illegal vigilante and it’s adorable.", "category": "Family", "emoji": "🐠" },
  { "title": "Monsters, Inc.", "clue": "Energy company pivots from screams to giggles after toddler breach.", "category": "Family", "emoji": "🐠" },
  { "title": "Ratatouille", "clue": "Rodent unionizes fine dining through hair-pull management.", "category": "Family", "emoji": "🐠" },
  { "title": "Cars", "clue": "Race car learns humility from detouring into Route Nostalgia.", "category": "Family", "emoji": "🐠" },
  { "title": "A Bug's Life", "clue": "Freelance ant hires circus to fix organized crime problem.", "category": "Family", "emoji": "🐠" },
  { "title": "Brave", "clue": "Daughter chooses cake-based communication; mother becomes bear.", "category": "Family", "emoji": "🐠" },
  { "title": "Turning Red", "clue": "Teenage emotions unlock kaiju-sized family meetings.", "category": "Family", "emoji": "🐠" },
  { "title": "Luca", "clue": "Sea kids summer in Italy pretending to be hydrophobic.", "category": "Family", "emoji": "🐠" },
  { "title": "Elemental", "clue": "Immigration allegory where water guy dates a literal fire hazard.", "category": "Family", "emoji": "🐠" },
  { "title": "The Good Dinosaur", "clue": "Timeline delay turns lizard into anxious farmer with pet human.", "category": "Family", "emoji": "🐠" },
  { "title": "The Princess and the Frog", "clue": "Entrepreneur kisses amphibian, catches startup curse.", "category": "Family", "emoji": "🐠" },
  { "title": "Tangled", "clue": "Tower influencer soft-launches freedom with lantern content.", "category": "Family", "emoji": "🐠" },
  { "title": "Wreck-It Ralph", "clue": "Villain quits toxic job; breaks several arcades finding himself.", "category": "Family", "emoji": "🐠" },
  { "title": "Despicable Me", "clue": "Moon-thief adopts three critics and catches feelings.", "category": "Family", "emoji": "🐠" },
  { "title": "How to Train Your Dragon", "clue": "Viking disrupts defense industry with dragon friendship.", "category": "Family", "emoji": "🐠" },
  { "title": "Paddington 2", "clue": "Polite immigrant bear reforms prison through marmalade and manners.", "category": "Family", "emoji": "🐠" },
  { "title": "The Mitchells vs. the Machines", "clue": "Family road trip becomes OS update for the apocalypse.", "category": "Family", "emoji": "🐠" },
  { "title": "Klaus", "clue": "Underperforming postman invents Christmas to hit KPIs.", "category": "Family", "emoji": "🐠" },
  { "title": "The Emperor's New Groove", "clue": "Management turns llama; HR suggests empathy training.", "category": "Family", "emoji": "🐠" },
  { "title": "Lilo & Stitch", "clue": "Sisters heal grief by adopting felony-level alien puppy.", "category": "Family", "emoji": "🐠" },
  { "title": "Mulan", "clue": "Daughter hacks patriarchy with sword and impeccable aim.", "category": "Family", "emoji": "🐠" },
  { "title": "The Iron Giant", "clue": "Boy teaches superweapon to choose non-murder setting.", "category": "Family", "emoji": "🐠" },
  { "title": "Spirited Away", "clue": "Child labor laws do not apply in bathhouses for ghosts.", "category": "Family", "emoji": "🐠" },
  { "title": "My Neighbor Totoro", "clue": "Country move comes with complimentary cat bus service.", "category": "Family", "emoji": "🐠" },
  { "title": "The LEGO Movie", "clue": "Ordinary brick is mistaken for startup founder of everything.", "category": "Family", "emoji": "🐠" },
  { "title": "The Little Mermaid", "clue": "Teen trades voice for legs and questionable surface culture.", "category": "Family", "emoji": "🐠" },
  { "title": "Beauty and the Beast", "clue": "Library card comes with furry roommate agreement.", "category": "Family", "emoji": "🐠" },
  { "title": "Aladdin", "clue": "Street magician leverages VC genie for social mobility.", "category": "Family", "emoji": "🐠" },
  { "title": "Peter Pan", "clue": "Flying boy recruits siblings for eternal bedtime avoidance.", "category": "Family", "emoji": "🐠" },
  { "title": "Cinderella", "clue": "Footwear trial resolves estate dispute and labor issues.", "category": "Family", "emoji": "🐠" },
  { "title": "Snow White and the Seven Dwarfs", "clue": "Miner roommates adopt apple-averse princess.", "category": "Family", "emoji": "🐠" },
  { "title": "The Jungle Book", "clue": "Wolf homeschooler taught survival by jazz bear.", "category": "Family", "emoji": "🐠" },
  { "title": "Pinocchio", "clue": "Wooden boy fails honesty patch notes repeatedly.", "category": "Family", "emoji": "🐠" },
  { "title": "101 Dalmatians", "clue": "Fashion mogul underestimates supply chain of puppies.", "category": "Family", "emoji": "🐠" },

  { "title": "Star Wars", "clue": "Farm boy discovers his father is a space fascist with breathing problems.", "category": "Sci-Fi", "emoji": "🤖" },
  { "title": "Titanic", "clue": "Rich girl and poor artist fall in love on sinking ship with insufficient lifeboats.", "category": "Emotional Damage", "emoji": "💔" }
];
